// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/p3ld3v/pkg/models/shared"
	"net/http"
)

type FindPetsByTagsRequest struct {
	// Tags to filter by
	Tags []string `queryParam:"style=form,explode=true,name=tags"`
}

func (o *FindPetsByTagsRequest) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

type FindPetsByTagsResponse struct {
	Body []byte
	// HTTP response content type for this operation
	ContentType string
	// successful operation
	Pets []shared.Pet
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *FindPetsByTagsResponse) GetBody() []byte {
	if o == nil {
		return nil
	}
	return o.Body
}

func (o *FindPetsByTagsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *FindPetsByTagsResponse) GetPets() []shared.Pet {
	if o == nil {
		return nil
	}
	return o.Pets
}

func (o *FindPetsByTagsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *FindPetsByTagsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
