// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetInventorySecurity struct {
	APIKey string `security:"scheme,type=apiKey,subtype=header,name=api_key"`
}

func (o *GetInventorySecurity) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

type GetInventoryResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful operation
	GetInventory200ApplicationJSONObject map[string]int
}

func (o *GetInventoryResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetInventoryResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetInventoryResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetInventoryResponse) GetGetInventory200ApplicationJSONObject() map[string]int {
	if o == nil {
		return nil
	}
	return o.GetInventory200ApplicationJSONObject
}
