// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UpdateUserRawRequest struct {
	// Update an existent user in the store
	RequestBody []byte `request:"mediaType=application/xml"`
	// name that need to be deleted
	Username string `pathParam:"style=simple,explode=false,name=username"`
}

func (o *UpdateUserRawRequest) GetRequestBody() []byte {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *UpdateUserRawRequest) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

type UpdateUserRawResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UpdateUserRawResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateUserRawResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateUserRawResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
