// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UpdatePetWithFormRequest struct {
	// Name of pet that needs to be updated
	Name *string `queryParam:"style=form,explode=true,name=name"`
	// ID of pet that needs to be updated
	PetID int64 `pathParam:"style=simple,explode=false,name=petId"`
	// Status of pet that needs to be updated
	Status *string `queryParam:"style=form,explode=true,name=status"`
}

func (o *UpdatePetWithFormRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdatePetWithFormRequest) GetPetID() int64 {
	if o == nil {
		return 0
	}
	return o.PetID
}

func (o *UpdatePetWithFormRequest) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type UpdatePetWithFormResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UpdatePetWithFormResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdatePetWithFormResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdatePetWithFormResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
